### ISSUE TITLE
DCM4CHEE pluging for openmediavault

### ISSUE THREAD

**Issue by sherifsafwfats** [nroduit/openmediavault-dcm4chee#1]
Dear all I can not access the web3 page with the default admin password , any help

**Comment by mc-hack** [comment]
Same problem after clean install

**Comment by nroduit** [comment]
See this [post](https://groups.google.com/d/msg/dcm4che/yyMIpAq4pyE/nbg1yaunBAAJ)

**Comment by nroduit** [comment]
This is fixed with openmediavault-dcm4chee_4.0.1 that uses postgres database instead of mysql.
